comment モデルのバリデーションの設定とテスト実装
danof-1105/wonderful_portal pull request #13
Opened 2021-04-22 09:57 UTC by t-ehara

## 概要
- 

## タスク内容
- 

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub の Files changed で差分を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 実装画面
- スクリーンショットなどを貼り付け

## その他参考情報
### 実装する上で参考にしたサイト
- []()

### ドキュメント
- []()

### その他
- なし

2021-04-22 11:15 UTC, KazusaNakagawa commented on spec/factories/comments.rb
> +    body { Faker::Lorem.sentence }
お試し

2021-04-23 04:37 UTC, danof-1105 commented on spec/models/comment_spec.rb
>    pending "add some examples to (or delete) #{__FILE__}"
ここ削除お願いします

2021-04-23 04:37 UTC, danof-1105 commented on spec/models/comment_spec.rb
> +      expect(comment).to be_valid
subjectを使ったテストにするよみやすくてよいと思います！

2021-04-23 08:03 UTC, daishiman requested changes

2021-04-23 08:03 UTC, daishiman commented on spec/factories/user_directories.rb
> -    user_directory { nil }
りくさんのブランチをマージしたら良さそうですね。

2021-04-23 08:03 UTC, daishiman commented on spec/models/comment_spec.rb
> +      expect(comment).to be_valid
こちらもりくさんの user, user_directories の FactoryBot を使えそうですね。

2021-04-23 08:03 UTC, daishiman commented on spec/models/comment_spec.rb
> +  let(:document) { create(:document, title: "Title", body: "Body", writer_id: user.id, owner: user, user_directory_id: user_directory.id) }
owner: user → owner_id: user.id では？

2021-04-23 08:03 UTC, daishiman commented on spec/models/comment_spec.rb
> +    it "エラーする" do
「エラーする」というよりも、「comment を作成できない」の方が表現としては適切かなと…

2021-04-23 15:04 UTC, danof-1105 reviewed
コメント抜けてたので追加しました、解説も入れたいのでまた時間あわせてペアプログラミングしてみましょうか！

2021-04-23 15:04 UTC, danof-1105 commented on spec/models/comment_spec.rb
> +  let(:document) { create(:document, title: "Title", body: "Body", writer_id: user.id, owner: user, user_directory_id: user_directory.id) }
> let(:user_directory) { create(:user_directory, name: "user1", user_id: user.id) }

```
let(:user_directory) { create(:user_directory, name: "user1", user: user) }
```
あとnameがuser1だとユーザー名っぽいのでディレクトリーっぽい名前にした方がよいかと！

> let(:document) { create(:document, title: "Title", body: "Body", writer_id: user.id, owner: user, user_directory_id: user_directory.id) }

```
 let(:document) { create(:document, title: "Title", body: "Body", writer: user, owner: user, user_directory: user_directory) }
```

が一般的な書き方かなと、以下同じ

2021-04-23 15:22 UTC, t-ehara commented on spec/models/comment_spec.rb
> +    it "エラーする" do
了解です！

2021-04-23 15:27 UTC, t-ehara commented on spec/models/comment_spec.rb
> +    it "エラーする" do
了解しました！

2021-04-23 15:34 UTC, t-ehara commented on spec/models/comment_spec.rb
> +  let(:document) { create(:document, title: "Title", body: "Body", writer_id: user.id, owner: user, user_directory_id: user_directory.id) }
> コメント抜けてたので追加しました、解説も入れたいのでまた時間あわせてペアプログラミングしてみましょうか！

了解です！
いつがよろしいでしょうか！

2021-04-24 01:28 UTC, daishiman commented on spec/factories/comments.rb
> +    body { Faker::Lorem.sentence }
他の方の FactoryBot がマージされたら、user, document の追記が必要そうですね。

2021-04-24 01:28 UTC, daishiman commented on spec/models/comment_spec.rb
> +    let(:user_directory) { create(:user_directory, user: user) }
user_directory の FactoryBot で user も作られるので、`, user: user` は不要かなと思いました。
すみませんが、実装して試したわけでないので、間違っていたら教えて下さい🙇‍♂️

2021-04-24 01:28 UTC, daishiman commented on spec/models/comment_spec.rb
> +    let(:document) { create(:document, writer: user, owner: user, user_directory: user_directory) }
ここも document の FactoryBot 出来たらリファクタリングできそうですね。

2021-04-24 01:28 UTC, daishiman commented on spec/models/comment_spec.rb
> +      let(:comment) { build(:comment, document: document, user: user) }
同じくです。

2021-04-24 01:28 UTC, daishiman commented on spec/models/comment_spec.rb
> +      let(:comment) { build(:comment, body: nil, document: document, user: user) }
同じくです。

2021-04-24 01:55 UTC, t-ehara commented on spec/models/comment_spec.rb
> +    let(:user_directory) { create(:user_directory, user: user) }
自分の勘違いだったらアレなのですが、前提として `user_directory.user` と `document.user` はイコールでなくても良いのですかね？
`user_directory` の FactoryBot で生成された `user` でもテスト通るとは思うのですが、それって`document.user` と`user_directory.user`が別人物になってしまうのですよね。

2021-04-24 02:01 UTC, t-ehara commented on spec/models/comment_spec.rb
> +    let(:user_directory) { create(:user_directory, user: user) }
`comment.user`は別人物でも問題ないので、FactoryBot でアソシエーションして再度 push しておきますー！

2021-04-24 04:06 UTC, merged