Userモデルのバリデーション、テストの作成
danof-1105/wonderful_portal pull request #16
Opened 2021-04-23 09:43 UTC by shota0011

## 概要
- Userモデルのバリデーションの設定とテストを実装

## タスク内容
### バリデーションの設定
- Userモデルのname（20文字以内）に文字制限を追記

### Userモデルのテストを実装
- 正常系
  - 必要な情報が入力されている時
  - nameが20文字以内の時
- 異常系
  - nameが入力されていないの時
  - emailが入力されていないの時
  - passwordが入力されていないの時
  - nameが21文字以上の時

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub の Files changed で差分を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

### その他
- なし

2021-04-23 09:46 UTC, danof-1105 commented on spec/models/user_spec.rb
> +        expect(subject).to raise_error(ActiveRecord::RecordInvalid)
具体的なエラー内容を指定したテストの方がよいですね
以下同じです

2021-04-23 10:44 UTC, KazusaNakagawa commented on spec/factories/users.rb
> +    password { Faker::Internet.password(min_length: 8) }
文字制限もしっかり設定していてイイと思いました😄

2021-04-23 10:48 UTC, KazusaNakagawa approved these changes
**LGTM**です!!

2021-04-23 10:48 UTC, KazusaNakagawa commented on spec/models/user_spec.rb
> +        expect(subject).to raise_error(ActiveRecord::RecordInvalid)
同じくみやすくてよいと思います!

2021-04-23 12:16 UTC, daishiman requested changes
だのふさんのレビュー内容と同じく、validation を設定している部分は異常系のテストを書いたほうがいいのかなと思いました。

2021-04-23 12:16 UTC, daishiman commented on app/models/user.rb
> +  validates :name, presence: true, length: { maximum: 20 }
user_name は文字数制限なかったような？

2021-04-23 12:16 UTC, daishiman commented on spec/factories/users.rb
> +    password { Faker::Internet.password(min_length: 8) }
`config.password_length = 6..128` なのでこの範囲で指定するほうがいいのかなと思いました。

2021-04-23 15:36 UTC, shota0011 commented on app/models/user.rb
> +  validates :name, presence: true, length: { maximum: 20 }
nameの文字数をある程度絞るという話になって、とりあえず20文字に制限するという話が出ていました！

>  だのふさん　【テーブル設計：コメント内】
>  nameは文字数ある程度絞りたいですね、どれくらいが適切だろう🤔

間違えていたら、教えて下さい！

2021-04-23 15:45 UTC, danof-1105 commented on spec/models/user_spec.rb
> +        expect(subject.errors.errors[0].type).to eq :blank
すみません、これは僕の伝え方のミスなのですが、こちらもdetailsの方を使った方が良いですね！

2021-04-24 00:54 UTC, daishiman commented on app/models/user.rb
> +  validates :name, presence: true, length: { maximum: 20 }
すみません。
文字数制限は directory 関係の name だけだと勘違いしていました。
今永さんが質問されていましたね。
すみませんでした🙇‍♂️

2021-04-24 02:53 UTC, danof-1105 commented
LGTMです！

2021-04-24 04:19 UTC, daishiman approved these changes

2021-04-24 04:20 UTC, KazusaNakagawa approved these changes

2021-04-24 09:41 UTC, merged